### ISSUE TITLE
Check are not showing when the workflow triggers on a pull_request event

### ISSUE THREAD

**Issue by geesara-aet** [LouisBrunner/checks-action#12]
I have created a workflow to build and test some code. Added separate checks to check the status of build and test steps. This works fine when the workflow triggers on "push" event.It will display the status of build and test steps . But when it triggers on pull_request event, it only shows the overall status of the workflow.
When triggered on pull_request event
    pull_request:
      branches: [ develop,experimental ]
      types: [ assigned, opened, synchronize, reopened,edited ]
![image](https://user-images.githubusercontent.com/59476240/96690606-85c6e900-13a1-11eb-9d7c-8ccf6a65e49c.png)

When triggered on push. Only change is adding a push event trigger
    push:
        branches: [ "branch_name" ]
![image](https://user-images.githubusercontent.com/59476240/96691676-cf640380-13a2-11eb-8c58-4c90684e8d7e.png)

**Comment by LouisBrunner** [comment]
Hi @geesara-aet, thank you for your report!

Do you have a repo with that issue which you can share, it will make it easier for me to debug/fix.

**Comment by geesara-aet** [comment]
Im sorry @LouisBrunner , This is a private repo belong to a client.

**Comment by alaa-nassef** [comment]
@LouisBrunner I would like to report the same issue and give some more details. When I report a check failure, like this
<img width="429" alt="Screen Shot 2020-11-05 at 11 45 32 AM" src="https://user-images.githubusercontent.com/22524855/98225103-facb1e80-1f5c-11eb-8070-8e04ffd745aa.png">
It is reported correctly in the PR
<img width="869" alt="Screen Shot 2020-11-05 at 11 44 58 AM" src="https://user-images.githubusercontent.com/22524855/98225236-28b06300-1f5d-11eb-941b-9b94db61e587.png">

However, when I report it as successful, like below
<img width="419" alt="Screen Shot 2020-11-05 at 11 47 57 AM" src="https://user-images.githubusercontent.com/22524855/98225340-454c9b00-1f5d-11eb-8dc6-6885a8dd93cf.png">
Status goes back to `Expected` in the PR, and all of the other ones that were reported as queued are removed!
<img width="869" alt="Screen Shot 2020-11-05 at 11 48 52 AM" src="https://user-images.githubusercontent.com/22524855/98225448-631a0000-1f5d-11eb-913a-b5afae4455aa.png">

Workflow snippet below
```yaml
name: Verify PR

on: pull_request
env:
  name: PR-${{ github.run_id }}-${{ github.run_number }}

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Deploy UT Check
      uses: LouisBrunner/checks-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy UT Succeeds
        status: queued
    - name: Setup Frontend Lint Check
      uses: LouisBrunner/checks-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Frontend Lint OK
        status: queued
    - name: Setup Frontend UT check
      uses: LouisBrunner/checks-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Frontend UT Succeeds
        status: queued
    - name: Setup Deploy IT Check
      uses: LouisBrunner/checks-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy IT Succeeds
        status: queued
    - name: Setup Frontend IT Check
      uses: LouisBrunner/checks-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Frontend IT Succeeds
        status: queued
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install aws cli
      uses: isbang/setup-awscli@v0.1.0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install deploy module dependencies
      run: npm ci
      working-directory: ./deploy
    - name: Build deploy module
      run: npm run build
      working-directory: ./deploy
    - name: Deploy UT Check In Progress
      uses: LouisBrunner/checks-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy UT Succeeds
        status: in_progress
    - name: Execute UT on deploy module
      id: dep-ut
      run: npm run test:ci
      working-directory: ./deploy
    - name: Deploy UT Check Succeeds
      uses: LouisBrunner/checks-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy UT Succeeds
        conclusion: success
    - name: Deploy UT Check Fails
      uses: LouisBrunner/checks-action@v1.1.0
      if: always() && steps.dep-ut.outcome == 'failure'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy UT Succeeds
        conclusion: failure
```
