### ISSUE TITLE
You must authenticate via a GitHub App

### ISSUE THREAD

**Issue by bandlachiranjeevi** [LouisBrunner/checks-action#141]
Please help me how to authenticate using github token

**Comment by bandlachiranjeevi** [comment]
You must authenticate via a GitHub App

**Comment by bandlachiranjeevi** [comment]
While using github actions it is able generate summary.md file . but unable to publish into Pull request page
it is showing **You must authenticate via a GitHub App**

**Comment by LouisBrunner** [comment]
Hi,

I think you are referring to this issue (triggering actions from a fork through a pull request): https://github.com/LouisBrunner/checks-action/issues/35#issuecomment-1237317411

There are a bunch of examples and explanations how to solve this in there, otherwise please feel free to reopen.

**Comment by JorensM** [comment]
@LouisBrunner Hello I am getting this error message though I'm not triggering an action from a fork but instead on my own repo. This is what my actions file looks like:

```
name: Run tests

on: pull_request

defaults:
 run:
  working-directory: ./app
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
    - uses: LouisBrunner/checks-action@v1.6.1
      if: always()
      with:
        token: ${{ secrets.GH_TOKEN }}
        name: Test XYZ
        conclusion: ${{ job.status }}
        output: |
          {"summary":"${{ steps.test.outputs.summary }}"}
```

I tried both with the new token type and the old one and granted all permissions. On the classic token type I'm getting the error `You must authenticate via a GitHub App` and with the new token type I'm getting `Resource not accessible by personal access token`

**Comment by LouisBrunner** [comment]
@JorensM What if you use `secrets.GITHUB_TOKEN`?

**Comment by JorensM** [comment]
@LouisBrunner I have my token saved with the name `GH_TOKEN` because when I tried saving it as `GITHUB_TOKEN` I got a message that I can't create secrets that start with the word `GITHUB`

**Comment by JorensM** [comment]
@LouisBrunner To be clear, I'm setting up the secret in the correct way? I go to Repo settings > Secrets and variables > Actions > Add token to Repository Secrets

**Comment by LouisBrunner** [comment]
`GITHUB_TOKEN` is a secret created automatically by Github, see https://docs.github.com/en/actions/security-guides/automatic-token-authentication

Most of the time you should be using it and not one created manually. Check the updated README for reference if you get permissions errors: https://github.com/LouisBrunner/checks-action?tab=readme-ov-file#permissions

**Comment by JorensM** [comment]
@LouisBrunner Thanks for clarifying, I didn't know there's a special secret token. I tried replacing `secrets.GH_TOKEN` with `secrets.GITHUB_TOKEN` and now I am getting `Resource not accessible by integration`.

This is what my `.yaml` file looks like:

```
name: Run tests

on: pull_request

defaults:
 run:
  working-directory: ./app
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
    - uses: LouisBrunner/checks-action@v1.6.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test XYZ
        conclusion: ${{ job.status }}
        output: |
          {"summary":"${{ steps.test.outputs.summary }}"}
```
