### ISSUE TITLE
Checks appear under a different workflow

### ISSUE THREAD

**Issue by khaeru** [LouisBrunner/checks-action#17]
Thanks for the useful action! It works well, but I'm having trouble configuring it properly to overcome a minor weirdness in the effects. Perhaps this is just my limited knowledge of the API semantics.

I have two workflow files. In [cq.yml](https://github.com/transportenergy/database/blob/2626f4c798e39b8541085c0c693bb045cae25286/.github/workflows/cq.yml) (this is trimmed to illustrate the issue):
```yaml
name: Code quality
# ...
jobs:
  lint:
    # Various stuff; doesn't use checks-action
```

In [pytest.yml](https://github.com/transportenergy/database/blob/2626f4c798e39b8541085c0c693bb045cae25286/.github/workflows/pytest.yml):
```yaml
name: Test suite & diagnostics
# ...
jobs:
  pytest:
    # Job configuration that includes...
    steps:
    # Other steps
    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        name: Upload historical database & diagnostics
```

See here: https://github.com/transportenergy/database/pull/64/checks

What I expect: that the check output appears under the "Test suite & diagnostics" section with the three other jobs corresponding to the file in which appears (the action is actually used *within* one of these jobs).

Instead, I observe: it appears under the "Code quality" section defined by the *other* file.

Is there a simple way to avoid this?
