### ISSUE TITLE
Checks show against the wrong workflow

### ISSUE THREAD

**Issue by dpp23** [LouisBrunner/checks-action#20]
I have 2 workflows one of which contains this as the last step:

```
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.plan.outputs.summary }}
          conclusion: ${{ job.status }}
          output: |
            {"summary": "${{ steps.plan.outputs.url }}"}
```

The check created by the `checks-action` gets connected to the other workflow. Is there a setting I can tweak to attach it the the current workflow?
