### ISSUE TITLE
PR is not udpated when running on a `workflow_run`

### ISSUE THREAD

**Issue by vincentbernat** [LouisBrunner/checks-action#22]
Hey!

When running on a workflow run, the PR is not updated with the check. It seems it is not easy to get the PR number in this case, so I don't have an easy solution.

```yaml
on:
  workflow_run:
    workflows:
      - examples

jobs: ...
```
